# Copyright (C) 2023 the project owner
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#!/usr/bin/env python3
"""
Delia Authentication Setup Helper

Helps configure Microsoft 365 OAuth for Delia MCP Server.
Run this script to generate the necessary environment variables.
"""

import os
import secrets
import uuid
from pathlib import Path

def generate_jwt_secret():
    """Generate a secure JWT secret."""
    return secrets.token_urlsafe(32)

def setup_oauth():
    """Interactive OAuth setup for Microsoft 365."""
    print("Delia Microsoft 365 OAuth Setup")
    print("=" * 50)
    print()

    print("This will help you configure Microsoft 365 OAuth authentication.")
    print("You'll need to create an Azure App Registration first.")
    print()

    # Check if already configured
    if os.getenv("MICROSOFT_CLIENT_ID"):
        print("WARNING: Microsoft OAuth appears to already be configured.")
        overwrite = input("Overwrite existing configuration? (y/N): ").lower().strip()
        if overwrite != 'y':
            print("Setup cancelled.")
            return

    print("Step 1: Create Azure App Registration")
    print("   1. Go to https://portal.azure.com")
    print("   2. Navigate to 'Azure Active Directory' → 'App registrations'")
    print("   3. Click 'New registration'")
    print("   4. Name: 'Delia MCP Server'")
    print("   5. Supported account types: 'Accounts in this organizational directory only'")
    print("   6. Redirect URI: http://localhost:8000/auth/microsoft/callback")
    print()

    client_id = input("Enter your Azure Client ID: ").strip()
    if not client_id:
        print("ERROR: Client ID is required.")
        return

    client_secret = input("Enter your Azure Client Secret: ").strip()
    if not client_secret:
        print("ERROR: Client Secret is required.")
        return

    redirect_url = input("Redirect URL [http://localhost:8000/auth/microsoft/callback]: ").strip()
    if not redirect_url:
        redirect_url = "http://localhost:8000/auth/microsoft/callback"

    # Generate JWT secret
    jwt_secret = generate_jwt_secret()

    print()
    print("Configuration generated!")
    print()

    # Create .env file
    env_file = Path(".env")
    env_content = f"""# Delia Authentication Configuration
# Generated by setup_auth.py

# Enable authentication
DELIA_AUTH_ENABLED=true

# JWT Configuration
DELIA_JWT_SECRET={jwt_secret}

# Microsoft 365 OAuth
MICROSOFT_CLIENT_ID={client_id}
MICROSOFT_CLIENT_SECRET={client_secret}
MICROSOFT_REDIRECT_URL={redirect_url}
"""

    env_file.write_text(env_content)
    print(f"Created .env file with configuration")
    print()

    print("Next steps:")
    print("   1. Load the environment: source .env")
    print("   2. Start the server: uv run python mcp_server.py --transport http --port 8000")
    print("   3. Visit: http://localhost:8000/auth/microsoft/login")
    print("   4. Sign in with your Microsoft 365 account")
    print()

    print("Security Notes:")
    print("   - Keep the JWT secret secure and don't commit it")
    print("   - The .env file is already in .gitignore")
    print("   - Use HTTPS in production")
    print()

def setup_basic_auth():
    """Setup basic username/password authentication."""
    print("Delia Basic Authentication Setup")
    print("=" * 50)
    print()

    # Generate JWT secret
    jwt_secret = generate_jwt_secret()

    env_file = Path(".env")
    env_content = f"""# Delia Basic Authentication Configuration
# Generated by setup_auth.py

# Enable authentication
DELIA_AUTH_ENABLED=true

# JWT Configuration
DELIA_JWT_SECRET={jwt_secret}
"""

    env_file.write_text(env_content)
    print("Created .env file with basic authentication")
    print()

    print("Next steps:")
    print("   1. Load the environment: source .env")
    print("   2. Start the server: uv run python mcp_server.py --transport http --port 8000")
    print("   3. Register a user: curl -X POST http://localhost:8000/auth/register \\")
    print("       -H 'Content-Type: application/json' \\")
    print("       -d '{\"email\": \"admin@example.com\", \"password\": \"securepassword\"}'")
    print("   4. Login: curl -X POST http://localhost:8000/auth/jwt/login \\")
    print("       -H 'Content-Type: application/json' \\")
    print("       -d '{\"username\": \"admin@example.com\", \"password\": \"securepassword\"}'")
    print()

def main():
    print("Delia Authentication Setup")
    print("=" * 40)
    print()
    print("Choose authentication method:")
    print("1. Microsoft 365 OAuth (Enterprise)")
    print("2. Basic Username/Password")
    print()

    choice = input("Enter choice (1 or 2): ").strip()

    if choice == "1":
        setup_oauth()
    elif choice == "2":
        setup_basic_auth()
    else:
        print("Invalid choice. Please run again.")

if __name__ == "__main__":
    main()
